SRCS=AudioPluginUtil.cpp \
Plugin_OvenMit.cpp
OBJS=$(SRCS:.cpp=.o)
OUTPUT=../../builds/unity/Plugins/Win64/libOvenMit.dll
CXXFLAGS=-I. -O2 -fPIC
LDFLAGS=-shared -fPIC
# CXXFLAGS=-fvisibility=hidden -I. -O3 -ffast-math -fPIC -Wl,-Bstatic -Wl,-Bdynamic -Wl,--as-needed
# LDFLAGS=-shared -rdynamic -fPIC
CXX=x86_64-w64-mingw32-g++-win32

all: $(OUTPUT)

clean:
	rm -f $(OUTPUT) $(OBJS)

$(OUTPUT): $(OBJS)
	$(CXX) $(LDFLAGS) -o $(OUTPUT) $(OBJS)

.cpp.o:
	$(CXX) $(CXXFLAGS) -c $<
